export type JupitermossPlace = {
  id: string
  name: string
  neighborhood: string
  city: string
  rating: number
  reviewCount: number
  etaMinutes: number
  distanceKm: number
  priceTier: "$" | "$$" | "$$$"
  tags: string[]
  dogPerks: string[]
  menuHighlights: string[]
  openUntil: string
  mapX: number
  mapY: number
}

export const jupitermossPlaces: JupitermossPlace[] = [
  {
    id: "paws-and-pour",
    name: "Paws & Pour Cafe",
    neighborhood: "Kreuzberg",
    city: "Berlin",
    rating: 4.8,
    reviewCount: 231,
    etaMinutes: 14,
    distanceKm: 1.2,
    priceTier: "$$",
    tags: ["Brunch", "Outdoor Patio", "Dog Treat Bar"],
    dogPerks: ["Water stations", "Leash hooks at every table", "Free welcome biscuit"],
    menuHighlights: ["Pumpkin pup-cup", "Grain bowl", "Iced oat latte"],
    openUntil: "9:00 PM",
    mapX: 24,
    mapY: 38,
  },
  {
    id: "tail-wag-tacos",
    name: "Tail Wag Tacos",
    neighborhood: "Friedrichshain",
    city: "Berlin",
    rating: 4.6,
    reviewCount: 180,
    etaMinutes: 18,
    distanceKm: 1.7,
    priceTier: "$",
    tags: ["Street Food", "Quick Pickup", "Dog Friendly"],
    dogPerks: ["Shade canopy", "Reusable water bowls", "Paw wipe station"],
    menuHighlights: ["Mushroom taco", "Smoky beans", "Lime agua fresca"],
    openUntil: "11:30 PM",
    mapX: 54,
    mapY: 30,
  },
  {
    id: "good-boy-bakery",
    name: "Good Boy Bakery",
    neighborhood: "Prenzlauer Berg",
    city: "Berlin",
    rating: 4.9,
    reviewCount: 342,
    etaMinutes: 11,
    distanceKm: 0.9,
    priceTier: "$$",
    tags: ["Bakery", "Morning", "House-made Treats"],
    dogPerks: ["Seasonal dog pastry menu", "Indoor dog corner", "Toy basket"],
    menuHighlights: ["Seeded sourdough", "Cardamom bun", "Peanut biscuit"],
    openUntil: "6:30 PM",
    mapX: 36,
    mapY: 56,
  },
  {
    id: "park-side-bowls",
    name: "Park Side Bowls",
    neighborhood: "Neukolln",
    city: "Berlin",
    rating: 4.5,
    reviewCount: 127,
    etaMinutes: 20,
    distanceKm: 2.3,
    priceTier: "$$",
    tags: ["Healthy", "Grain Bowls", "Park Nearby"],
    dogPerks: ["Fast takeout lane", "Dog snack add-on", "Outdoor seating"],
    menuHighlights: ["Falafel bowl", "Sesame tofu", "Green tahini"],
    openUntil: "10:00 PM",
    mapX: 67,
    mapY: 52,
  },
  {
    id: "leash-and-ladle",
    name: "Leash & Ladle",
    neighborhood: "Mitte",
    city: "Berlin",
    rating: 4.7,
    reviewCount: 204,
    etaMinutes: 16,
    distanceKm: 1.5,
    priceTier: "$$$",
    tags: ["Dinner", "Seasonal Menu", "Quiet Patio"],
    dogPerks: ["Reserved dog seating", "House broth for dogs", "Calm zone tables"],
    menuHighlights: ["Roasted squash", "Braised lentils", "Crispy potatoes"],
    openUntil: "10:30 PM",
    mapX: 44,
    mapY: 24,
  },
  {
    id: "the-sniff-stop",
    name: "The Sniff Stop",
    neighborhood: "Wedding",
    city: "Berlin",
    rating: 4.4,
    reviewCount: 96,
    etaMinutes: 22,
    distanceKm: 2.8,
    priceTier: "$",
    tags: ["Coffee", "Pastries", "Grab & Go"],
    dogPerks: ["Express pickup shelf", "Dog tag photo wall", "Toy refill box"],
    menuHighlights: ["Flat white", "Apple tart", "Mini pup loaf"],
    openUntil: "8:00 PM",
    mapX: 71,
    mapY: 18,
  },
  {
    id: "bark-bistro",
    name: "Bark Bistro",
    neighborhood: "Charlottenburg",
    city: "Berlin",
    rating: 4.7,
    reviewCount: 212,
    etaMinutes: 19,
    distanceKm: 2.1,
    priceTier: "$$$",
    tags: ["Bistro", "Evening", "Dog Menu"],
    dogPerks: ["Dog tasting plate", "Heated patio zone", "Quiet seating"],
    menuHighlights: ["Mushroom gnocchi", "Citrus salad", "House focaccia"],
    openUntil: "11:00 PM",
    mapX: 58,
    mapY: 42,
  },
  {
    id: "fetch-and-fritter",
    name: "Fetch & Fritter",
    neighborhood: "Moabit",
    city: "Berlin",
    rating: 4.3,
    reviewCount: 84,
    etaMinutes: 24,
    distanceKm: 3.1,
    priceTier: "$",
    tags: ["Snacks", "Fried Bites", "Takeaway"],
    dogPerks: ["Quick leash rail", "Outdoor benches", "Dog water refill"],
    menuHighlights: ["Corn fritter", "Spicy potatoes", "Lemon soda"],
    openUntil: "9:30 PM",
    mapX: 18,
    mapY: 22,
  },
  {
    id: "puppy-picnic-pantry",
    name: "Puppy Picnic Pantry",
    neighborhood: "Tempelhof",
    city: "Berlin",
    rating: 4.5,
    reviewCount: 133,
    etaMinutes: 17,
    distanceKm: 1.9,
    priceTier: "$$",
    tags: ["Picnic", "Sandwiches", "Park Packs"],
    dogPerks: ["Portable water cups", "Picnic blanket loan", "Treat pouch add-on"],
    menuHighlights: ["Caprese sandwich", "Herb potato salad", "Berry iced tea"],
    openUntil: "8:30 PM",
    mapX: 29,
    mapY: 64,
  },
  {
    id: "wagyu-and-walks",
    name: "Wagyu & Walks",
    neighborhood: "Schoneberg",
    city: "Berlin",
    rating: 4.8,
    reviewCount: 261,
    etaMinutes: 21,
    distanceKm: 2.6,
    priceTier: "$$$",
    tags: ["Steakhouse", "Date Night", "Dog Lounge"],
    dogPerks: ["Indoor dog lounge", "Cooling mats", "Custom dog bowls"],
    menuHighlights: ["Seared mushrooms", "Pepper steak", "Potato mash"],
    openUntil: "11:45 PM",
    mapX: 61,
    mapY: 67,
  },
  {
    id: "sit-stay-soup",
    name: "Sit Stay Soup",
    neighborhood: "Lichtenberg",
    city: "Berlin",
    rating: 4.2,
    reviewCount: 59,
    etaMinutes: 26,
    distanceKm: 3.4,
    priceTier: "$",
    tags: ["Soup Bar", "Comfort Food", "Budget"],
    dogPerks: ["Warm dog broth", "Covered waiting area", "Refill station"],
    menuHighlights: ["Tomato basil", "Lentil stew", "Garlic toast"],
    openUntil: "9:00 PM",
    mapX: 79,
    mapY: 48,
  },
  {
    id: "canine-corner-pizza",
    name: "Canine Corner Pizza",
    neighborhood: "Pankow",
    city: "Berlin",
    rating: 4.6,
    reviewCount: 176,
    etaMinutes: 15,
    distanceKm: 1.4,
    priceTier: "$$",
    tags: ["Pizza", "Family", "Dog Treats"],
    dogPerks: ["Dog-safe crust bites", "Leash hooks", "Photo booth wall"],
    menuHighlights: ["Margherita", "Truffle mushroom", "Garlic knots"],
    openUntil: "10:45 PM",
    mapX: 33,
    mapY: 14,
  },
  {
    id: "muddy-paws-noodle-club",
    name: "Muddy Paws Noodle Club",
    neighborhood: "Tiergarten",
    city: "Berlin",
    rating: 4.7,
    reviewCount: 198,
    etaMinutes: 13,
    distanceKm: 1.1,
    priceTier: "$$",
    tags: ["Noodles", "Lunch", "Fast Service"],
    dogPerks: ["Shaded patio", "Paw cleaning wipes", "Dog bowl station"],
    menuHighlights: ["Miso ramen", "Sesame noodles", "Cucumber salad"],
    openUntil: "10:00 PM",
    mapX: 48,
    mapY: 58,
  },
  {
    id: "hound-harvest",
    name: "Hound Harvest",
    neighborhood: "Steglitz",
    city: "Berlin",
    rating: 4.4,
    reviewCount: 118,
    etaMinutes: 23,
    distanceKm: 2.9,
    priceTier: "$$",
    tags: ["Seasonal", "Bowls", "Organic"],
    dogPerks: ["Dog veggie snack", "Wide aisle seating", "Calm corner"],
    menuHighlights: ["Roasted carrot bowl", "Lemon couscous", "Herb dip"],
    openUntil: "9:45 PM",
    mapX: 22,
    mapY: 48,
  },
]

export function getJupitermossPlace(placeId: string) {
  return jupitermossPlaces.find((place) => place.id === placeId)
}
